source 'https://rubygems.org'
ruby "~> 1.9.3"

gem 'rake'
gem 'asciidoctor', '1.5.0'

gem 'json'
gem 'awesome_print'

gem 'asciidoctor-epub3', '1.0.0.alpha.2'
gem 'asciidoctor-pdf'

gem 'coderay', '1.1.2'
gem 'pygments.rb'
gem 'thread_safe'
gem 'epubcheck'
